#!/usr/bin/bash

URL="https://www.vocabulary.com/dictionary"
DICT_PATH="$HOME/.config/vocablookup/dict"

word=$(cat $DICT_PATH | rofi -dmenu -e "Vocabulary search")
if [[ -n $word ]]; then
	xdg-open $URL/$word
fi

